import type { NewCombination } from "../schema";

export const combosData: NewCombination[] = [
  {
    id: "H3",
    name: "H3",
    displayName: "Horizontal 3",
    pattern: [
      [0, 0],
      [0, 1],
      [0, 2],
    ],
    baseMultiplier: 2,
    detectionOrder: 1,
    isActive: true,
    description: "3 symboles identiques alignés horizontalement",
  },
  {
    id: "V3",
    name: "V3",
    displayName: "Vertical 3",
    pattern: [
      [0, 0],
      [1, 0],
      [2, 0],
    ],
    baseMultiplier: 2,
    detectionOrder: 2,
    isActive: true,
    description: "3 symboles identiques alignés verticalement",
  },
  {
    id: "D3",
    name: "D3",
    displayName: "Diagonal 3",
    pattern: [
      [0, 0],
      [1, 1],
      [2, 2],
    ],
    baseMultiplier: 2.5,
    detectionOrder: 3,
    isActive: true,
    description: "3 symboles identiques en diagonal",
  },
  {
    id: "H4",
    name: "H4",
    displayName: "Horizontal 4",
    pattern: [
      [0, 0],
      [0, 1],
      [0, 2],
      [0, 3],
    ],
    baseMultiplier: 4,
    detectionOrder: 4,
    isActive: true,
    description: "4 symboles identiques alignés horizontalement",
  },
  {
    id: "H5",
    name: "H5",
    displayName: "Horizontal 5",
    pattern: [
      [0, 0],
      [0, 1],
      [0, 2],
      [0, 3],
      [0, 4],
    ],
    baseMultiplier: 8,
    detectionOrder: 5,
    isActive: true,
    description: "5 symboles identiques alignés horizontalement",
  },
  {
    id: "V",
    name: "V",
    displayName: "Full Vertical",
    pattern: [
      [0, 0],
      [1, 0],
      [2, 0],
    ],
    baseMultiplier: 6,
    detectionOrder: 6,
    isActive: true,
    description: "Colonne complète de symboles identiques",
  },
  {
    id: "V_BIS",
    name: "V_BIS",
    displayName: "Vertical Bis",
    pattern: [
      [0, 1],
      [1, 1],
      [2, 1],
    ],
    baseMultiplier: 6,
    detectionOrder: 7,
    isActive: true,
    description: "Colonne complète de symboles identiques (variante)",
  },
  {
    id: "TRI",
    name: "TRI",
    displayName: "Triangle",
    pattern: [
      [0, 0],
      [1, 0],
      [1, 1],
    ],
    baseMultiplier: 3,
    detectionOrder: 8,
    isActive: true,
    description: "Triangle de 3 symboles identiques",
  },
  {
    id: "OEIL",
    name: "OEIL",
    displayName: "Oeil",
    pattern: [
      [0, 1],
      [1, 0],
      [1, 1],
      [1, 2],
      [2, 1],
    ],
    baseMultiplier: 10,
    detectionOrder: 9,
    isActive: true,
    description: "Pattern en forme d'oeil (croix + centre)",
  },
  {
    id: "JACKPOT",
    name: "JACKPOT",
    displayName: "Jackpot",
    pattern: [], // Full grid, detected separately
    baseMultiplier: 50,
    detectionOrder: 10,
    isActive: true,
    description: "Grille complète d'un seul symbole",
  },
  {
    id: "MULTI",
    name: "MULTI",
    displayName: "Multi-Combo",
    pattern: [], // Multiple combos at once
    baseMultiplier: 5,
    detectionOrder: 11,
    isActive: true,
    description: "Plusieurs combinaisons simultanées",
  },
];

