import type { NewJoker } from "../schema";

export const jokersData: NewJoker[] = [
  {
    id: "weight_boost",
    name: "Boost de Symbole",
    description: "Augmente le poids d'un symbole au choix de 20%",
    rarity: "common",
    basePrice: 3,
    effects: [{ type: "increase_weight", value: 20, target: "player_choice" }],
    tags: ["weight", "symbol"],
    sellValue: 1,
  },
  {
    id: "flat_chance",
    name: "Chance Pure",
    description: "Augmente la chance de 3 points",
    rarity: "common",
    basePrice: 4,
    effects: [{ type: "increase_chance", value: 3 }],
    tags: ["chance"],
    sellValue: 1,
  },
  {
    id: "combo_multiplier",
    name: "Multiplicateur de Combo",
    description: "Augmente le multiplicateur de combinaison de 0.5",
    rarity: "uncommon",
    basePrice: 5,
    effects: [{ type: "increase_combo_multiplier", value: 0.5 }],
    tags: ["multiplier", "combo"],
    sellValue: 2,
  },
  {
    id: "symbol_multiplier",
    name: "Multiplicateur de Symbole",
    description: "Augmente le multiplicateur de symbole de 0.3",
    rarity: "uncommon",
    basePrice: 5,
    effects: [{ type: "increase_symbol_multiplier", value: 0.3 }],
    tags: ["multiplier", "symbol"],
    sellValue: 2,
  },
  {
    id: "free_rerolls",
    name: "Rerolls Gratuits",
    description: "Ajoute 2 rerolls gratuits en boutique",
    rarity: "rare",
    basePrice: 8,
    effects: [{ type: "free_rerolls", value: 2 }],
    tags: ["shop", "reroll"],
    sellValue: 3,
  },
  {
    id: "debt_master",
    name: "Maître de la Dette",
    description: "Autorise à s'endetter pour acheter des jokers",
    rarity: "epic",
    basePrice: 12,
    effects: [{ type: "allow_debt", value: 1 }],
    tags: ["shop", "economy"],
    sellValue: 5,
  },
  {
    id: "resale_value",
    name: "Expert Marchand",
    description: "Augmente la valeur de revente des jokers de 1$ par niveau",
    rarity: "uncommon",
    basePrice: 6,
    effects: [{ type: "increase_sell_value", value: 1 }],
    tags: ["economy", "shop"],
    sellValue: 2,
  },
  {
    id: "extra_spins",
    name: "Spins Bonus",
    description: "Ajoute 1 spin supplémentaire par niveau",
    rarity: "rare",
    basePrice: 10,
    effects: [{ type: "extra_spins", value: 1 }],
    tags: ["spins"],
    sellValue: 4,
  },
  {
    id: "jqk_connection",
    name: "Connexion Royale",
    description:
      "Si 10, J, Q font partie d'une connection, ajoute +1 multiplicateur",
    rarity: "uncommon",
    basePrice: 7,
    effects: [
      { type: "conditional_multiplier", value: 1, target: "10,J,Q" },
    ],
    tags: ["multiplier", "conditional"],
    sellValue: 3,
  },
  {
    id: "ka_connection",
    name: "Connexion Haute",
    description: "Si K, A font partie d'une connection, ajoute +1.5 multiplicateur",
    rarity: "rare",
    basePrice: 9,
    effects: [{ type: "conditional_multiplier", value: 1.5, target: "K,A" }],
    tags: ["multiplier", "conditional"],
    sellValue: 4,
  },
  {
    id: "lucky_combo",
    name: "Combo Chanceux",
    description:
      "1 chance sur 4 d'augmenter le multiplicateur de combo permanent lors d'une connection",
    rarity: "epic",
    basePrice: 15,
    effects: [
      { type: "random_permanent_multiplier", value: 0.25 },
    ],
    tags: ["multiplier", "chance", "permanent"],
    sellValue: 6,
  },
  {
    id: "level_rewards",
    name: "Récompenses de Niveau",
    description: "Octroie 3$ supplémentaires à chaque fin de niveau",
    rarity: "common",
    basePrice: 4,
    effects: [{ type: "bonus_dollars_per_level", value: 3 }],
    tags: ["economy", "level"],
    sellValue: 1,
  },
  {
    id: "risky_spins",
    name: "Spins Risqués",
    description: "Ajoute 2 spins mais diminue la chance de 5",
    rarity: "uncommon",
    basePrice: 5,
    effects: [
      { type: "extra_spins", value: 2 },
      { type: "decrease_chance", value: 5 },
    ],
    tags: ["spins", "chance", "risky"],
    sellValue: 2,
  },
  {
    id: "rich_symbols",
    name: "Symboles Riches",
    description:
      "Ajoute +0.1 multiplicateur de symbole par tranche de 5$ possédés",
    rarity: "rare",
    basePrice: 10,
    effects: [
      { type: "multiplier_per_dollar", value: 0.1, target: "symbol" },
    ],
    tags: ["multiplier", "economy", "scaling"],
    sellValue: 4,
  },
  {
    id: "rich_combos",
    name: "Combos Riches",
    description:
      "Ajoute +0.1 multiplicateur de combo par tranche de 5$ possédés",
    rarity: "epic",
    basePrice: 14,
    effects: [{ type: "multiplier_per_dollar", value: 0.1, target: "combo" }],
    tags: ["multiplier", "economy", "scaling"],
    sellValue: 6,
  },
  {
    id: "exp_booster",
    name: "Boost d'XP",
    description: "Augmente l'XP et les $ de fin de niveau de 50%",
    rarity: "uncommon",
    basePrice: 6,
    effects: [
      { type: "increase_xp_percent", value: 50 },
      { type: "increase_dollars_percent", value: 50 },
    ],
    tags: ["xp", "economy", "level"],
    sellValue: 2,
  },
  {
    id: "building_chance",
    name: "Chance Croissante",
    description:
      "Chance augmentée de +1 à chaque combo (max +20 cumulable)",
    rarity: "rare",
    basePrice: 8,
    effects: [{ type: "chance_per_combo", value: 1 }],
    tags: ["chance", "scaling", "combo"],
    sellValue: 3,
  },
  {
    id: "basic_dollar_drop",
    name: "Symboles Généreux (Basiques)",
    description:
      "Chaque symbole basique qui connecte a 25% de chance de donner 2$ supplémentaires",
    rarity: "uncommon",
    basePrice: 5,
    effects: [
      {
        type: "symbol_drop",
        value: 2,
        target: "10,J,Q,K,A",
      },
    ],
    tags: ["economy", "symbol", "chance"],
    sellValue: 2,
  },
  {
    id: "premium_token_drop",
    name: "Symboles Généreux (Premium)",
    description:
      "Chaque symbole premium qui connecte a 25% de chance de donner 50 jetons supplémentaires",
    rarity: "rare",
    basePrice: 9,
    effects: [
      {
        type: "symbol_drop",
        value: 50,
        target: "P1,P2,P3",
      },
    ],
    tags: ["tokens", "symbol", "chance"],
    sellValue: 4,
  },
  {
    id: "persistent_chance",
    name: "Chance Persistante",
    description:
      "Lorsqu'un spin n'est pas gagnant, chance +2 (cumulable jusqu'à +20, ne se réinitialise pas)",
    rarity: "epic",
    basePrice: 12,
    effects: [{ type: "persistent_chance_on_loss", value: 2 }],
    tags: ["chance", "scaling", "persistent"],
    sellValue: 5,
  },
  {
    id: "premium_combo_boost",
    name: "Boost Premium",
    description:
      "Une connexion de symboles premium ajoute x1.5 au multiplicateur de combo (cumulable, multiplicatif)",
    rarity: "rare",
    basePrice: 10,
    effects: [
      {
        type: "combo_multiplier_on_symbol_type",
        value: 1.5,
        target: "premium",
      },
    ],
    tags: ["multiplier", "combo", "premium"],
    sellValue: 4,
  },
  {
    id: "basic_combo_boost",
    name: "Boost Basique",
    description:
      "Une connexion de symboles basiques ajoute x1.5 au multiplicateur de combo (cumulable, multiplicatif)",
    rarity: "uncommon",
    basePrice: 7,
    effects: [
      {
        type: "combo_multiplier_on_symbol_type",
        value: 1.5,
        target: "basic",
      },
    ],
    tags: ["multiplier", "combo", "basic"],
    sellValue: 3,
  },
  {
    id: "jqk_unification",
    name: "Unification Royale",
    description:
      "Les 10, J, Q comptent comme un seul symbole et connectent entre eux (prennent la valeur la plus élevée)",
    rarity: "legendary",
    basePrice: 20,
    effects: [{ type: "unify_symbols", value: 1, target: "10,J,Q" }],
    tags: ["symbol", "connection", "legendary"],
    sellValue: 10,
  },
  {
    id: "bonus_picker",
    name: "Cueilleur de Bonus",
    description:
      "Le joueur choisit parmi 3 bonus à équiper, puis le joker est détruit",
    rarity: "epic",
    basePrice: 15,
    effects: [{ type: "grant_bonus_choice", value: 3 }],
    tags: ["bonus", "one-time"],
    sellValue: 0,
  },
  {
    id: "rarity_upgrade",
    name: "Amélioration de Rareté",
    description:
      "Augmente la rareté d'un bonus équipé de 1 cran, puis ce joker est détruit",
    rarity: "legendary",
    basePrice: 25,
    effects: [{ type: "upgrade_bonus_rarity", value: 1 }],
    tags: ["bonus", "one-time", "legendary"],
    sellValue: 0,
  },
];

