import type { NewSymbol } from "../schema";

export const symbolsData: NewSymbol[] = [
  // Basic symbols (symboles de base)
  {
    id: "10",
    name: "10",
    type: "basic",
    baseWeight: 15,
    baseValue: 1,
    baseMultiplier: 1,
    icon: "🔟",
    color: "#64748b",
  },
  {
    id: "J",
    name: "J",
    type: "basic",
    baseWeight: 12,
    baseValue: 2,
    baseMultiplier: 1,
    icon: "🃏",
    color: "#64748b",
  },
  {
    id: "Q",
    name: "Q",
    type: "basic",
    baseWeight: 10,
    baseValue: 3,
    baseMultiplier: 1,
    icon: "👑",
    color: "#64748b",
  },
  {
    id: "K",
    name: "K",
    type: "basic",
    baseWeight: 8,
    baseValue: 4,
    baseMultiplier: 1,
    icon: "🤴",
    color: "#64748b",
  },
  {
    id: "A",
    name: "A",
    type: "basic",
    baseWeight: 6,
    baseValue: 5,
    baseMultiplier: 1,
    icon: "🅰️",
    color: "#64748b",
  },
  // Premium symbols (symboles premium)
  {
    id: "P1",
    name: "P1",
    type: "premium",
    baseWeight: 5,
    baseValue: 10,
    baseMultiplier: 1.5,
    icon: "💎",
    color: "#3b82f6",
  },
  {
    id: "P2",
    name: "P2",
    type: "premium",
    baseWeight: 3,
    baseValue: 15,
    baseMultiplier: 2,
    icon: "💰",
    color: "#8b5cf6",
  },
  {
    id: "P3",
    name: "P3",
    type: "premium",
    baseWeight: 2,
    baseValue: 25,
    baseMultiplier: 3,
    icon: "⭐",
    color: "#f59e0b",
  },
  // Bonus symbol
  {
    id: "B",
    name: "Bonus",
    type: "bonus",
    baseWeight: 1,
    baseValue: 0,
    baseMultiplier: 1,
    icon: "🎁",
    color: "#22c55e",
  },
];

